sonar.projectKey=bbog-cat-kata-backend
sonar.projectName=BBOG CAT Kata Backend
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

# TypeScript
sonar.inclusions=**/*.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/infrastructure-reference/**,**/lambda/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,test/**/*,**/lambda/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
