sonar.projectKey=kata_backend_project
sonar.projectName=Kata Backend Project
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

# TypeScript
sonar.inclusions=**/*.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/infrastructure/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,test/**/*
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
